version: '3'

services:
  zookeeper1:
    image: confluentinc/cp-zookeeper:7.6.0
    hostname: zookeeper1
    container_name: zookeeper1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zookeeper1:2888:3888;zookeeper2:2888:3888;zookeeper3:2888:3888
    volumes:
      - zookeeper:/var/lib/zookeeper/1
    networks:
      - kafka_network

  zookeeper2:
    image: confluentinc/cp-zookeeper:7.6.0
    hostname: zookeeper2
    container_name: zookeeper2
    ports:
      - "2182:2182"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2182
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_SERVERS: zookeeper1:2888:3888;zookeeper2:2888:3888;zookeeper3:2888:3888
    volumes:
      - zookeeper:/var/lib/zookeeper/2
    networks:
      - kafka_network

  zookeeper3:
    image: confluentinc/cp-zookeeper:7.6.0
    hostname: zookeeper3
    container_name: zookeeper3
    ports:
      - "2183:2183"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2183
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_SERVERS: zookeeper1:2888:3888;zookeeper2:2888:3888;zookeeper3:2888:3888
    volumes:
      - zookeeper:/var/lib/zookeeper/3
    networks:
      - kafka_network



  kafka1:
    image: confluentinc/cp-kafka:7.6.0
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092,DOCKER://host.docker.internal:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper1:2181,zookeeper2:2182,zookeeper3:2183"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    volumes:
      - kafka:/var/lib/kafka/1
    networks:
      - kafka_network
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3

  kafka2:
    image: confluentinc/cp-kafka:7.6.0
    hostname: kafka2
    container_name: kafka2
    ports:
      - "9093:9093"
      - "29093:29093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka2:19093,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9093,DOCKER://host.docker.internal:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper1:2181,zookeeper2:2182,zookeeper3:2183"
      KAFKA_BROKER_ID: 2
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    volumes:
      - kafka:/var/lib/kafka/2
    networks:
      - kafka_network
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3

  kafka3:
    image: confluentinc/cp-kafka:7.6.0
    hostname: kafka3
    container_name: kafka3
    ports:
      - "9094:9094"
      - "29094:29094"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka3:19094,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9094,DOCKER://host.docker.internal:29094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper1:2181,zookeeper2:2182,zookeeper3:2183"
      KAFKA_BROKER_ID: 3
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    volumes:
      - kafka:/var/lib/kafka/3
    networks:
      - kafka_network
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3

  kafka-gitops:
    image: devshawn/kafka-gitops:0.2.15
    hostname: kafka_gitops
    container_name: kafka_gitops
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka1:19092,kafka2:19093,kafka3:19094
      KAFKA_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_CLIENT_ID: gitops-user
    volumes:
      - ./kafka-setup:/gitops
    command: kafka-gitops -v -f /gitops/state.yml apply
    networks:
      - kafka_network
    depends_on:
      - kafka1
      - kafka2
      - kafka3



  authorization-db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: authorization
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - authorizationPostgres:/var/lib/postgresql/data
    networks:
      - backend

  authorization-migrations:
    image: liquibase/liquibase:4.25
    command:
      - --changelog-file=master.yml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://authorization-db:5432/authorization
      - --username=postgres
      - --password=postgres
      - update
    volumes:
      - ./migrations/authorization:/liquibase/changelog
    networks:
      - backend
    depends_on:
      - authorization-db



  link-db:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: link
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - linkPostgres:/var/lib/postgresql/data
    networks:
      - backend

  link-migrations:
    image: liquibase/liquibase:4.25
    command:
      - --changelog-file=master.yml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://link-db:5432/link
      - --username=postgres
      - --password=postgres
      - update
    volumes:
      - ./migrations/link:/liquibase/changelog
    networks:
      - backend
    depends_on:
      - link-db



  steam-db:
    image: postgres:16
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: steam
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - steamPostgres:/var/lib/postgresql/data
    networks:
      - backend

  steam-migrations:
    image: liquibase/liquibase:4.25
    command:
      - --changelog-file=master.yml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://steam-db:5432/steam
      - --username=postgres
      - --password=postgres
      - update
    volumes:
      - ./migrations/steam:/liquibase/changelog
    networks:
      - backend
    depends_on:
      - steam-db


  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"


volumes:
  kafka: { }
  zookeeper: { }
  authorizationPostgres: { }
  linkPostgres: { }
  steamPostgres: { }
  prometheus-data: { }

networks:
  kafka_network: { }
  backend: { }
