global:
  scrape_interval: 5s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: bot-listener
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:8090"]

  - job_name: bot-sender
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:8091"]

  - job_name: authorization
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:8092"]

  - job_name: links
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:8093"]

  - job_name: steam
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:8094"]

