bot:
  token: ${TELEGRAM_TOKEN}

kafka:
  messages-topic:
    name: send-messages
    bootstrap-address: http://localhost:9092
    listener-id: bot-listener
  messages_dlq-topic:
    name: send-messages_dlq
    bootstrap-address: http://localhost:9092
    listener-id: bot-listener
  authorization-topic:
    name: authorization
    bootstrap-address: http://localhost:9092
    listener-id: bot-listener

spring:
  application:
    name: bot-listener
  jackson:
    time-zone: UTC

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus
      path-mapping:
        prometheus: /metrics

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
