bot:
  token: ${TELEGRAM_TOKEN}

kafka:
  messages-topic:
    name: send-messages
    bootstrap-address: http://localhost:9092
    listener-id: bot-listener
  authorization-topic:
    name: authorization
    bootstrap-address: http://localhost:9092
    listener-id: bot-listener

spring:
  application:
    name: bot-service
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
